const caffeineDB = [
 { name: "녹차 (티백 1잔)", caffeine: 30, sugar: 0, category: "차" },
 { name: "홍차 (티백 1잔)", caffeine: 45, sugar: 0, category: "차" },
 { name: "서울우유 초콜릿 우유 (200ml)", caffeine: 5, sugar: 20, category: "음료" },
 { name: "포카리스웨트 이온워터(제로)", caffeine: 0, sugar: 0, category: "음료" },
 { name: "데자와 밀크티", caffeine: 15, sugar: 26, category: "음료" },
 { name: "리얼골드 드링크", caffeine: 20, sugar: 21, category: "음료" },
 { name: "밀크티 흑당버블티(편의점)", caffeine: 30, sugar: 45, category: "음료" },
 { name: "공차 타로 밀크티", caffeine: 50, sugar: 25, category: "음료" },
 { name: "공차 블랙 밀크티", caffeine: 128, sugar: 3, category: "음료" },

 { name: "코카콜라 (355ml)", caffeine: 35, sugar: 39, category: "탄산음료" },
 { name: "코카콜라 제로 (355ml)", caffeine: 42, sugar: 0, category: "탄산음료" },
 { name: "펩시 콜라 (355ml)", caffeine: 38, sugar: 41, category: "탄산음료" },
 { name: "펩시 제로 (355ml)", caffeine: 43, sugar: 0, category: "탄산음료" },

 { name: "몬스터 에너지(초록)", caffeine: 100, sugar: 41, category: "에너지드링크" },
 { name: "몬스터 에너지 울트라 (흰색)", caffeine: 100, sugar: 0, category: "에너지드링크" },
 { name: "몬스터 에너지 울트라 시트라", caffeine: 100, sugar: 0, category: "에너지드링크" },
 { name: "몬스터 에너지 울트라 파라다이스", caffeine: 100, sugar: 0, category: "에너지드링크" },
 { name: "몬스터 파이프라인 펀치", caffeine: 160, sugar: 50, category: "에너지드링크" },
 { name: "몬스터 망고 로코", caffeine: 152, sugar: 46, category: "에너지드링크" },
 { name: "넷플릭스 에너지드링크", caffeine: 200, sugar: 0, category: "에너지드링크" },
 { name: "얼박사", caffeine: 100, sugar: 32, category: "에너지드링크" },

 { name: "핫식스 오리지널 (250ml)", caffeine: 60, sugar: 30, category: "에너지드링크" },
 { name: "핫식스 더킹 포스", caffeine: 100, sugar: null, category: "에너지드링크" },
 { name: "핫식스 더킹 제로", caffeine: 100, sugar: 0, category: "에너지드링크" },
 { name: "핫식스 더킹 러쉬", caffeine: 100, sugar: null, category: "에너지드링크" },
 { name: "핫식스 더킹 퍼플 그레이프", caffeine: 100, sugar: null, category: "에너지드링크" },
 { name: "핫식스 더킹 파워", caffeine: 100, sugar: null, category: "에너지드링크" },
 { name: "핫식스 더킹 아이스피치 제로", caffeine: 100, sugar: 0, category: "에너지드링크" },

 { name: "스타벅스 아메리카노 (Tall)", caffeine: 150, sugar: 0, category: "커피" },
 { name: "스타벅스 콜드브루 (Tall)", caffeine: 155, sugar: 0, category: "커피" },
 { name: "스타벅스 콜드브루 라떼 (Tall)", caffeine: 150, sugar: 11, category: "커피" },
 { name: "스타벅스 돌체 라떼 (Tall)", caffeine: 150, sugar: 32, category: "커피" },
 { name: "스타벅스 바닐라 라떼 (Tall)", caffeine: 150, sugar: 35, category: "커피" },
 { name: "스타벅스 카페모카 (Tall)", caffeine: 95, sugar: 31, category: "커피" },
 { name: "스타벅스 제주말차라떼", caffeine: 60, sugar: 20, category: "커피" },
 { name: "스타벅스 디카페인 아메리카노 (Tall)", caffeine: 10, sugar: 0, category: "커피" },
 { name: "스타벅스 더블샷 에스프레소(캔)", caffeine: 120, sugar: 10, category: "캔/병커피" },

 { name: "빽다방 아메리카노(Ice)", caffeine: 293, sugar: 0, category: "커피" },
 { name: "빽다방 원조커피(Ice)", caffeine: 220, sugar: 47, category: "커피" },
 { name: "빽다방 아이스 라떼", caffeine: 204, sugar: 18, category: "커피" },
 { name: "빽다방 아샷추", caffeine: 100, sugar: 63, category: "커피" },

 { name: "메가커피 아메리카노 (Regular)", caffeine: 110, sugar: 0, category: "커피" },
 { name: "메가커피 아샷추", caffeine: 123, sugar: 62, category: "커피" },
 { name: "메가커피 바닐라라떼 (L)", caffeine: 174, sugar: 34, category: "커피" },
 { name: "메가커피 카페모카 (L)", caffeine: 174, sugar: 48, category: "커피" },

 { name: "이디야 아메리카노 (Regular)", caffeine: 100, sugar: 0, category: "커피" },
 { name: "이디야 바닐라라떼", caffeine: 174, sugar: 32, category: "커피" },
 { name: "이디야 콜드브루 라떼", caffeine: 210, sugar: 14, category: "커피" },
 { name: "이디야 아샷추 복숭아 (L)", caffeine: 101, sugar: 57, category: "음료" },
 { name: "이디야 아샷추 복숭아 (EX)", caffeine: 110, sugar: 79, category: "음료" },
 { name: "이디야 제로슈가 아샷추 (L)", caffeine: 111, sugar: 0, category: "음료" },
 { name: "이디야 제로슈가 아샷추 (EX)", caffeine: 126, sugar: 0, category: "음료" },

 { name: "컴포즈 아메리카노 (Hot)", caffeine: 156, sugar: null, category: "커피" },
 { name: "컴포즈 아메리카노 (Ice)", caffeine: 156, sugar: null, category: "커피" },
 { name: "컴포즈 카페라떼 (Hot)", caffeine: 208, sugar: null, category: "커피" },
 { name: "컴포즈 카페라떼 (Ice)", caffeine: 208, sugar: null, category: "커피" },
 { name: "컴포즈 바닐라라떼 (Hot)", caffeine: 208, sugar: null, category: "커피" },
 { name: "컴포즈 바닐라라떼 (Ice)", caffeine: 208, sugar: null, category: "커피" },
 { name: "컴포즈 카라멜마키아토 (Hot)", caffeine: 208, sugar: null, category: "커피" },
 { name: "컴포즈 카라멜마키아토 (Ice)", caffeine: 208, sugar: null, category: "커피" },
 { name: "컴포즈 카페모카 (Hot)", caffeine: 208, sugar: null, category: "커피" },
 { name: "컴포즈 카페모카 (Ice)", caffeine: 208, sugar: null, category: "커피" },

 { name: "투썸 아메리카노 (Regular)", caffeine: 184, sugar: 0, category: "커피" },
 { name: "커피빈 아메리카노 (Tall)", caffeine: 200, sugar: 0, category: "커피" },
 { name: "폴 바셋 아메리카노 (Tall)", caffeine: 180, sugar: 0, category: "커피" },
 { name: "탐앤탐스 아메리카노 (Tall)", caffeine: 120, sugar: 0, category: "커피" },

 { name: "레쓰비 마일드 커피", caffeine: 74, sugar: 12, category: "캔/병커피" },
 { name: "레쓰비 카페타임", caffeine: 47, sugar: 10, category: "캔/병커피" },
 { name: "조지아 오리지널", caffeine: 99, sugar: 13, category: "캔/병커피" },
 { name: "조지아 에메랄드 마운틴 블랙", caffeine: 165, sugar: 0, category: "캔/병커피" },
 { name: "조지아 에메랄드 마운틴 라떼", caffeine: 155, sugar: 22, category: "캔/병커피" },
 { name: "조지아 크래프트 카페라떼", caffeine: 229, sugar: 33, category: "캔/병커피" },
 { name: "칸타타 스위트 아메리카노", caffeine: 81, sugar: 9, category: "캔/병커피" },
 { name: "칸타타 콘트라베이스 블랙", caffeine: 170, sugar: 0, category: "캔/병커피" },
 { name: "칸타타 프리미엄 라떼", caffeine: 150, sugar: 22, category: "캔/병커피" },
 { name: "맥심 티오피 블랙", caffeine: 96, sugar: 0, category: "캔/병커피" },

 { name: "맥심 커피믹스(1봉)", caffeine: 55, sugar: 6, category: "믹스커피" },

 { name: "샷 추가 (에스프레소 1샷)", caffeine: 75, sugar: 0, category: "추가옵션" },
 { name: "박카스 F", caffeine: 30, sugar: 15, category: "자양강장제" }
];

// ✅ caffeineDB는 전역 변수로 자동 사용 가능
